# Generated by Django 5.1.4 on 2025-01-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("typewriter", "0003_textdata_typewriter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textdata",
            name="typewriter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="typewriter.typewriter",
            ),
        ),
    ]
