# secrets.py
# Put API Keys here

MQQT_SERVER = YOUR_MQQT_SERVER_URL
MQQT_USERNAME = YOUR_MQQT_USERNAME
MQQT_PASSWORD = YOUR_MQQT_PASSWORD

# we use https://www.cloudmailin.com/
SMTP_SERVER = YOUR_SMTP_SERVER
SMTP_USER = YOUR_SMTP_USER
SMTP_PASSWORD = YOUR_SMTP_PASSWORD